name: Build image on push or PR
on: ["push", "pull_request"]

jobs:
    build:

        runs-on: ubuntu-22.04
        
        steps:
        
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Dependencies
          run: |
              sudo apt update
              sudo apt install binfmt-support qemu-user-static quilt debootstrap apt-cacher-ng libarchive-tools qemu-utils gpg pigz

        - name: Set image name
          run: |
              CITADEL_OS_VERSION="$(git describe --tags)"
              IMAGE_NAME="citadel-os-${CITADEL_OS_VERSION}"
              echo "CITADEL_OS_VERSION=$CITADEL_OS_VERSION"  >> $GITHUB_ENV
              echo "IMAGE_NAME=$IMAGE_NAME"  >> $GITHUB_ENV

        - name: Run build script
          run: |
              echo "Building $IMAGE_NAME"
              sudo docker system prune --all --force
              sudo docker logout ghcr.io
              sudo IMG_FILENAME=$IMAGE_NAME ARCHIVE_FILENAME=$IMAGE_NAME CITADEL_OS_VERSION=$CITADEL_OS_VERSION ./build.sh
        - name: Copy ZIP to current working dir
          run: cp deploy/*.zip ./

        - name: Debug current working dir
          run: ls -la

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            path: ${{ env.IMAGE_NAME }}.zip
            name: ${{ env.IMAGE_NAME }}.zip
